name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        TELEGRAM_TOKEN: ${{ secrets.QUICKMEET_TELEGRAM_TOKEN }}
      run: |
        export TELEGRAM_TOKEN=$TELEGRAM_TOKEN
        python -m pytest tests/
    - name: Build Docker image
      if: ${{ github.event_name == 'release' }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          sudo docker build --tag yevzman/quickmeet .
          sudo docker push yevzman/quickmeet
